const football = [
    {
      id: 1,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCVk7BxWWq074sM4UaXpB6mBa6OjYhnSZBzsLTXbHu4qDIDK10XY_WrQQun-7fBiAg1vo&usqp=CAU',
      name:'Lionel Messi',
      age:'36 years',
     country:'argentina',
     description:'Lionel Messi is a football player from Argentina who plays for FC Barcelona. He has won the Ballon D Or the annual award given to the best player in the world 7 times 2022 FIFA World Cup winner and an Olympic gold medal winner in 2008 He was born in 1987 in Rosario Argentinas third-biggest city',
    },
    {
        id: 2,
      image: 'https://images2.minutemediacdn.com/image/upload/c_crop,w_3000,h_1687,x_0,y_270/c_fill,w_720,ar_16:9,f_auto,q_auto,g_auto/images/voltaxMediaLibrary/mmsport/90min_en_international_web/01h3emnsm3t80qvaxdxn.jpg',
      name:'Marcus Rashford  ',
      age:'25 years',
     country:' United Kingdom.',   
    description:'Marcus Rashford MBE is an English professional footballer who plays as a forward for Premier League club Manchester United and the England national team. A product of the Manchester United youth system, he joined the club at the age of seven',
    },
    {
      id: 3,
      name: 'Cristiano Ronaldo',
      age: '38 years',
      image: 'https://images.sportsbrief.com/images/1120/1a831ab318908535.jpeg?v=1',
      description: 'Cristiano Ronaldo dos Santos Aveiro GOIH ComM is a Portuguese professional footballer who plays as a forward for and captains both Saudi Professional League club Al Nassr and the Portugal national team.',
    },
    {
      id: 4,
      name: 'Vini Jr.',
      age: '22 years',
      country:'Brazilian',
      image: 'https://assets.laliga.com/assets/2021/12/29/xlarge/f755886dce5c30880054da5a3a5b38da.jpeg',
      description: 'Vinícius José Paixão de Oliveira Júnior, commonly known as Vinícius Júnior or Vini Jr., is a Brazilian professional footballer who plays as a winger for La Liga club Real Madrid and the Brazil national team.',
    },
    // {
    //   id: 5,
    //   name: 'Luka Modrić',
    //   country:' Croatian',
    //   age: '37 years',
    //   image
    //   description: 'Luka Modrić is a Croatian professional footballer who plays as a midfielder for La Liga club Real Madrid and captains the Croatia national team. He plays mainly as a central midfielder, but can also play as an attacking midfielder or as a defensive midfielder',
    // },
    {
      id: 6,
      name: 'Jude Bellingham',
      age:' 20 years',
      country:'British',
      image: 'https://biglysports.com/wp-content/uploads/2022/04/Jude-Bellingham-Biography-Childhood-Career-Life.jpg',
      description: 'Jude Victor William Bellingham is an English professional footballer who plays as a midfielder for La Liga club Real Madrid and the England national team',
    },
    {
      id: 7,
      name: 'Mason Mount',
      botanicalName: 'Citrullus lanatus',
      
      image: 'https://encrypted-tbn0.gstatic.com/licensed-image?q=tbn:ANd9GcQva4kBbuPPdzwTYCuxgKCqV8sar8-kNhFVTFu1KC3tpMGFG8lXJ8uqObWt-K8gc8LCaC-JvFnLlImiHSY',
      description: 'Watermelons are large, refreshing fruits with a high water content. They are perfect for hydration and are enjoyed during hot summer days.',
    },
    {
      id: 8,
      name: 'Bernardo Silva',
      age:'28 years',
      country:' Portuguese',
      image: 'https://tmssl.akamaized.net/images/foto/galerie/bernardo-silva-manchester-city-1603739071-49975.jpg?lm=1603739085',
      description: 'Bernardo Mota Veiga de Carvalho e Silva is a Portuguese professional footballer who plays as an attacking midfielder or winger for Premier League club Manchester City and the Portugal national team. Silva is known for his creativity, dribbling, stamina, versatility, and work-rate.',
    },
    {
      id: 9,
      name: 'Peach',
      botanicalName: 'Prunus persica',
      season: 'Summer',
      image: 'path/to/peach-image.jpg',
      description: 'Peaches are fuzzy, juicy fruits with a deliciously sweet flavor. They are rich in vitamins and minerals and are a delightful addition to various desserts and recipes.',
    },
    {
      id: 10,
      name: 'Pear',
      botanicalName: 'Pyrus communis',
      season: 'Autumn',
      image: 'path/to/pear-image.jpg',
      description: 'Pears are sweet and juicy fruits with a slightly grainy texture. They are rich in fiber, vitamin C, and antioxidants, making them a healthy choice for snacking or cooking.',
    },
    {
      id: 11,
      name: 'Cherry',
      botanicalName: 'Prunus avium',
      season: 'Spring',
      image: 'path/to/cherry-image.jpg',
      description: 'Cherries are small, vibrant fruits with a sweet and tart flavor. They are rich in antioxidants and have anti-inflammatory properties, making them a nutritious and delicious treat.',
    },
    {
      id: 12,
      name: 'Blueberry',
      botanicalName: 'Vaccinium corymbosum',
      season: 'Summer',
      image: 'path/to/blueberry-image.jpg',
      description: 'Blueberries are small, round berries with a sweet and tangy taste. They are packed with antioxidants and are often considered a superfood due to their numerous health benefits.',
    },
  ];
  
  